version: '3.8'

services:
  sleepy:
    build: .
    container_name: sleepy
    ports:
      - "127.0.0.1:9010:9010"
    volumes:
      - ./config.json:/app/config.json
      - ./static/favicon.ico:/app/static/favicon.ico   # 只映射这一个文件
    restart: always